import Header from '@/components/ui/Header.js'
import Footer from '@/components/ui/Footer.js'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import { CartProvider } from '@/contexts/CartContext.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Header/>
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  )
}
